HeThongNhaSach/Controllers/ChucvuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HeThongNhaSach.Models;
using System.Diagnostics;

namespace HeThongNhaSach.Controllers
{
    public class ChucvuController : Controller
    {
        private readonly HeThongNhaSachContext _context;

        public ChucvuController(HeThongNhaSachContext context)
        {
            _context = context;
        }

        // GET: Chucvu
        public async Task<IActionResult> Index()
        {
            return View(await _context.Chucvu.ToListAsync());
        }

        // GET: Chucvu/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chucvu = await _context.Chucvu
                .FirstOrDefaultAsync(m => m.Macv == id);
            if (chucvu == null)
            {
                return NotFound();
            }

            return View(chucvu);
        }

        // GET: Chucvu/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Chucvu/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Macv,Tencv,Taikhoan,Matkhau")] Chucvu chucvu)
        {
            if (ModelState.IsValid)
            {
                _context.Add(chucvu);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(chucvu);
        }

        // GET: Chucvu/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chucvu = await _context.Chucvu.FindAsync(id);
            if (chucvu == null)
            {
                return NotFound();
            }
            return View(chucvu);
        }

        // POST: Chucvu/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Macv,Tencv,Taikhoan,Matkhau")] Chucvu chucvu)
        {
            if (id != chucvu.Macv)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(chucvu);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ChucvuExists(chucvu.Macv))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(chucvu);
        }

        // GET: Chucvu/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chucvu = await _context.Chucvu
                .FirstOrDefaultAsync(m => m.Macv == id);
            if (chucvu == null)
            {
                return NotFound();
            }

            return View(chucvu);
        }

        // POST: Chucvu/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var chucvu = await _context.Chucvu.FindAsync(id);
            _context.Chucvu.Remove(chucvu);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ChucvuExists(int id)
        {
            return _context.Chucvu.Any(e => e.Macv == id);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HeThongNhaSach/Controllers/HoadonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HeThongNhaSach.Models;
<<<<<<< HEAD
using Microsoft.AspNetCore.Http;
=======
>>>>>>> a445a4153798aa13716d281869a69d9754782e61

namespace HeThongNhaSach.Controllers
{
    public class HoadonController : Controller
    {
        private readonly HeThongNhaSachContext _context;

        public HoadonController(HeThongNhaSachContext context)
        {
            _context = context;
        }

        // GET: Hoadon
        public async Task<IActionResult> Index()
        {
            return View(await _context.Hoadon.ToListAsync());
        }

        // GET: Hoadon/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hoadon = await _context.Hoadon
                .FirstOrDefaultAsync(m => m.Mahd == id);
            if (hoadon == null)
            {
                return NotFound();
            }

            return View(hoadon);
        }

        // GET: Hoadon/Create
        public IActionResult Create()
        {
<<<<<<< HEAD
            ViewBag.manv = HttpContext.Session.GetString("manv");
=======
>>>>>>> a445a4153798aa13716d281869a69d9754782e61
            return View();
        }

        // POST: Hoadon/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Mahd,Loaihd,Ngaylap,Manv,Tinhtrang")] Hoadon hoadon)
        {
            if (ModelState.IsValid)
            {
                _context.Add(hoadon);
                await _context.SaveChangesAsync();
<<<<<<< HEAD
                string mahd = hoadon.Mahd.ToString();
                HttpContext.Session.SetString("mahd", mahd);
                return Redirect("/Chitiethd/Create");
=======
                return RedirectToAction(nameof(Index));
>>>>>>> a445a4153798aa13716d281869a69d9754782e61
            }
            return View(hoadon);
        }

        // GET: Hoadon/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
<<<<<<< HEAD
            ViewBag.manv = HttpContext.Session.GetString("manv");
=======
>>>>>>> a445a4153798aa13716d281869a69d9754782e61

            var hoadon = await _context.Hoadon.FindAsync(id);
            if (hoadon == null)
            {
                return NotFound();
            }
            return View(hoadon);
        }

        // POST: Hoadon/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Mahd,Loaihd,Ngaylap,Manv,Tinhtrang")] Hoadon hoadon)
        {
            if (id != hoadon.Mahd)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(hoadon);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HoadonExists(hoadon.Mahd))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(hoadon);
        }

        // GET: Hoadon/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hoadon = await _context.Hoadon
                .FirstOrDefaultAsync(m => m.Mahd == id);
            if (hoadon == null)
            {
                return NotFound();
            }

            return View(hoadon);
        }

        // POST: Hoadon/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var hoadon = await _context.Hoadon.FindAsync(id);
            _context.Hoadon.Remove(hoadon);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HoadonExists(int id)
        {
            return _context.Hoadon.Any(e => e.Mahd == id);
        }
    }
}

HeThongNhaSach/Controllers/SachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HeThongNhaSach.Models;

namespace HeThongNhaSach.Controllers
{
    public class SachController : Controller
    {
        private readonly HeThongNhaSachContext _context;

        public SachController(HeThongNhaSachContext context)
        {
            _context = context;
        }

        // GET: Sach
        public async Task<IActionResult> Index()
        {
            var heThongNhaSachContext = _context.Sach.Include(s => s.MaloaiNavigation).Include(s => s.ManvNavigation).Include(s => s.ManxbNavigation);
            return View(await heThongNhaSachContext.ToListAsync());
        }

        // GET: Sach/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sach = await _context.Sach
                .Include(s => s.MaloaiNavigation)
                .Include(s => s.ManvNavigation)
                .Include(s => s.ManxbNavigation)
                .FirstOrDefaultAsync(m => m.Masach == id);
            if (sach == null)
            {
                return NotFound();
            }

            return View(sach);
        }

        // GET: Sach/Create
        public IActionResult Create()
        {
            ViewData["Maloai"] = new SelectList(_context.Loaisach, "Maloai", "Tenloai");
            ViewData["Manv"] = new SelectList(_context.Nhanvien, "Manv", "Hoten");
            ViewData["Manxb"] = new SelectList(_context.Nhaxuatban, "Manxb", "Tennxb");
            return View();
        }

        // POST: Sach/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Masach,Tensach,Tacgia,Isbn,Maloai,Manv,Manxb,Dongia,Soluong,Chietkhau,Ghichu")] Sach sach)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sach);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Maloai"] = new SelectList(_context.Loaisach, "Maloai", "Maloai", sach.Maloai);
            ViewData["Manv"] = new SelectList(_context.Nhanvien, "Manv", "Manv", sach.Manv);
            ViewData["Manxb"] = new SelectList(_context.Nhaxuatban, "Manxb", "Manxb", sach.Manxb);
            return View(sach);
        }

        // GET: Sach/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sach = await _context.Sach.FindAsync(id);
            if (sach == null)
            {
                return NotFound();
            }
            ViewData["Maloai"] = new SelectList(_context.Loaisach, "Maloai", "Maloai", sach.Maloai);
            ViewData["Manv"] = new SelectList(_context.Nhanvien, "Manv", "Manv", sach.Manv);
            ViewData["Manxb"] = new SelectList(_context.Nhaxuatban, "Manxb", "Manxb", sach.Manxb);
            return View(sach);
        }

        // POST: Sach/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Masach,Tensach,Tacgia,Isbn,Maloai,Manv,Manxb,Dongia,Soluong,Chietkhau,Ghichu")] Sach sach)
        {
            if (id != sach.Masach)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sach);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SachExists(sach.Masach))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Maloai"] = new SelectList(_context.Loaisach, "Maloai", "Maloai", sach.Maloai);
            ViewData["Manv"] = new SelectList(_context.Nhanvien, "Manv", "Manv", sach.Manv);
            ViewData["Manxb"] = new SelectList(_context.Nhaxuatban, "Manxb", "Manxb", sach.Manxb);
            return View(sach);
        }

        // GET: Sach/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sach = await _context.Sach
                .Include(s => s.MaloaiNavigation)
                .Include(s => s.ManvNavigation)
                .Include(s => s.ManxbNavigation)
                .FirstOrDefaultAsync(m => m.Masach == id);
            if (sach == null)
            {
                return NotFound();
            }

            return View(sach);
        }

        // POST: Sach/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sach = await _context.Sach.FindAsync(id);
            _context.Sach.Remove(sach);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SachExists(int id)
        {
            return _context.Sach.Any(e => e.Masach == id);
        }
    }
}

HeThongNhaSach/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HeThongNhaSach</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HeThongNhaSach</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                QUẢN LÝ
                            </a>
                            <div class="dropdown-menu" aria-labelledby="" id="">
<<<<<<< HEAD
                                <a class="dropdown-item" asp-area="" asp-controller="Chucvu" asp-action="Index">Chucvu</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Nhanvien" asp-action="Index">Nhanvien</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Loaisach" asp-action="Index">Loaisach</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Nhaxuatban" asp-action="Index">Nhaxuatban</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Sach" asp-action="Index">Sach</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Hoadon" asp-action="Index">Hoadon</a>
                                <a class="dropdown-item" asp-area="" asp-controller="PhieuNhap" asp-action="Index">Phiếu Nhập</a>

                                <a class="dropdown-item" asp-area="" asp-controller="Chitiethd" asp-action="Index">Chitiethd</a>
=======
                                <a class="dropdown-item" asp-area="" asp-controller="Chucvu" asp-action="Index">Chức vụ</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Nhanvien" asp-action="Index">Nhân viên</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Loaisach" asp-action="Index">Loại sách</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Nhaxuatban" asp-action="Index">Nhà xuất bản</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Sach" asp-action="Index">Sách</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Hoadon" asp-action="Index">Hoá đơn</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Chitiethd" asp-action="Index">Chi tiết hoá đơn</a>
>>>>>>> a445a4153798aa13716d281869a69d9754782e61
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                QUẢN LÝ 2
                            </a>
                            <div class="dropdown-menu" aria-labelledby="" id="">
                                <a class="dropdown-item" asp-area="" asp-controller="Nhasach" asp-action="Index">Nhasach</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Sachnhasach" asp-action="Index">Sachnhasach</a>

                            </div>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - HeThongNhaSach - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>